[general]
import = [
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/fonts.toml",
  "~/.config/alacritty/themes/no-clown-fiesta-dark.toml",
]

[cursor]
vi_mode_style = "Block"

[window]
option_as_alt = "OnlyLeft"

[env]
live_config_reload = "true"
