[general]
import = [
  "~/.config/alacritty/keybindings.toml",
  "~/.config/alacritty/fonts.toml",
  "~/.config/alacritty/themes/no_clown_fiesta_dark.toml",
]

[cursor]
vi_mode_style = "Block"

[window]
option_as_alt = "OnlyLeft"
