[font]
size = 10

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Medium Italic"
